spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog
      username: admin
      password: geekshirts

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
